name: FirstPlugin
version: 1.0
main: me.foont.firstplugin.FirstPlugin
api-version: 1.16
authors: [ foont ]
description: My first working plugin
depends: [Towny]
commands:
  buyracks1:
    description: Даёт первую казарму